// Regenerates src/assets/fonts/embedded.ts from the .ttf files next to it, for the certificate PDF
// (src/lib/certificate.ts). Embedding the fonts in the code means no file-system access at runtime, which
// Cloudflare Workers don't have. Run after adding or changing a font: node scripts/embed-fonts.mjs
import fs from "node:fs";
import path from "node:path";

const dir = path.join(import.meta.dirname, "../src/assets/fonts");
const files = fs.readdirSync(dir).filter((f) => f.endsWith(".ttf")).sort();
const lines = files.map((f) => `  ${JSON.stringify(f)}: ${JSON.stringify(fs.readFileSync(path.join(dir, f)).toString("base64"))},`);
fs.writeFileSync(path.join(dir, "embedded.ts"), [
  "// GENERATED by scripts/embed-fonts.mjs from the .ttf files in this folder. Do not edit by hand.",
  "// Base64 so the certificate PDF needs no file-system access (Cloudflare Workers have none).",
  "export const EMBEDDED_FONTS: Record<string, string> = {",
  ...lines,
  "};",
  "",
].join("\n"));
console.log(`Embedded ${files.length} fonts into src/assets/fonts/embedded.ts`);
